Changed get_class method to work for Image Streamer resources
HewlettPackard/oneview-puppet pull request #112
Opened 2017-02-17 18:59 UTC by marikrg

### Description
Changed get_class method from uri_parsing.rb to work for Image Streamer resources.

### Issues Resolved
This is required for Image Streamer resources which dependends on other resources.

For example Golden Image:
```puppet
data   => {
  buildPlanUri  => 'Name of the build plan'
}
```
After this change, an user will be able to provide a name instead of a URI for Image Streamer resources.

Required for #99 and some other Image Streamer resources to be implemented in future.

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

2017-02-20 11:31 UTC, fgbulsoni requested changes

2017-02-20 11:31 UTC, fgbulsoni commented on lib/puppet/provider/uri_parsing.rb
> +  is_image_streamer = OneviewSDK::ImageStreamer::Client == @client.class
How about
```ruby
sub_module = OneviewSDK::ImageStreamer::Client == @client.class ? 'ImageStreamer::' : ''
resource_name = "#{key.to_s[0].upcase}#{key[1..key.size - 4]}"
Object.const_get("OneviewSDK::#{sub_module}API#{@client.api_version}::#{resource_name}")

2017-02-20 17:48 UTC, fgbulsoni commented
Changes look good, but one thing that hit me is: Should we also worry about the `hardware_variant` here? Because with this we are adding the API namespace, but it will likely be using the default `C7000` at all times.

2017-02-20 18:19 UTC, marikrg commented
@fgbulsoni 
Yes, I agree.
Even I can't imagine a scenario which the Synergy class is not inheriting the `get` from C7000, I believe it must use the right namespace.
Should I consider the hardware variant for OneView only when the api_version >= 300?

2017-02-20 21:55 UTC, marikrg commented
I'm not adding the Hardware Variant for API Version 200, it breaks. :disappointed: 

```Could not evaluate: uninitialized constant OneviewSDK::API200::C7000```

2017-02-21 14:16 UTC, fgbulsoni approved these changes
Changes look good. :shipit:

2017-02-21 14:23 UTC, merged