Fix unit test
HewlettPackard/oneview-puppet pull request #113
Opened 2017-02-17 19:25 UTC by abiliogp

### Description
Fix unit tests on unexpected scenarios 

### Issues Resolved
#55 

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

2017-02-20 11:54 UTC, fgbulsoni requested changes
Lots of small changes here and there on the PR, on basically every file. 
Should try to look into the using the guard clause based on `api_version` for every synergy test file to not run against an `api_version` smaller than `300`.
Should move the instance creation, typically named `test` to a `let` instead of duplicating.
Should move the basic `find_by` and `exists?` calls to a `before_each`.
Should generally also look into the it examples and see what is being done and how could those be improved.

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_connection_template_synergy_spec.rb
> +describe provider_class, unit: true do
`, if: login[:api_version] >= 300`

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_connection_template_synergy_spec.rb
> +resourcetype = OneviewSDK.resource_named(:ConnectionTemplate, api_version, 'Synergy')
This will try to call Synergy for api 200. Best to to move this declaration to line `24~25` inside the describe provider_class

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_connection_template_synergy_spec.rb
> +      test = resourcetype.new(@client, name: resource['data']['name'])
test should be inside a `let` so it can be reused and removed from every `it`

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_connection_template_synergy_spec.rb
> +      allow(resourcetype).to receive(:find_by).and_return([test])
This should be inside a `before_each`

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_datacenter_synergy_spec.rb
> +    let(:provider) { resource.provider }
No need to redeclare the provider and instance `let`, should just move them out of a specific context.

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_datacenter_synergy_spec.rb
> +    let(:provider) { resource.provider }
Same as previous comment

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_datacenter_synergy_spec.rb
> +    it 'deletes the resource' do
This could have most lines removed from it after the modifications mentioned

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_drive_enclosure_synergy_spec.rb
> +resourcetype = OneviewSDK.resource_named(:DriveEnclosure, api_version, 'Synergy')
Move to line `25`

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_enclosure_group_synergy_spec.rb
> +resourcetype = OneviewSDK.resource_named(:EnclosureGroup, api_version, 'Synergy')
move to line `25`

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_enclosure_group_synergy_spec.rb
> +      test = resourcetype.new(@client, resource['data'])
Should be inside a `let`

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_enclosure_group_synergy_spec.rb
> +      allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
line 86~87 should be inside a `before_each`

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_enclosure_group_synergy_spec.rb
> +      test = resourcetype.new(@client, resource['data'])
remove

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_enclosure_group_synergy_spec.rb
> +      resource['data']['uri'] = '/rest/fake'
Remove everything except last line

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_enclosure_synergy_spec.rb
> +resourcetype = OneviewSDK.resource_named(:Enclosure, api_version, 'Synergy')
move to line `25`

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_enclosure_synergy_spec.rb
> +    it 'deletes the resource' do
refactor this

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_enclosure_synergy_spec.rb
> +    it 'should be able to work specifying a name instead of an uri' do
refactor this

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_enclosure_synergy_spec.rb
> +      it 'creates the resource' do
refactor

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_ethernet_network_synergy_spec.rb
> +resourcetype = OneviewSDK.resource_named(:EthernetNetwork, api_version, 'Synergy')
move to line `25`

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_ethernet_network_synergy_spec.rb
> +describe provider_class, unit: true do
Missing the guard clause

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_ethernet_network_synergy_spec.rb
> +    it 'deletes the resource' do
refactor

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_ethernet_network_synergy_spec.rb
> +      test = resourcetype.new(@client, resource['data'])
Again, move test to a `let`

2017-02-20 11:54 UTC, fgbulsoni commented on spec/unit/provider/oneview_ethernet_network_synergy_spec.rb
> +      allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
Move these to a `before_each`

2017-02-23 13:50 UTC, fgbulsoni commented
Is this PR being updated? I still see `refactor` messages and checking the code it seems like it remains as it was. 
Main things to look out for are: unnecessary `test` declaration inside `it`s, when we are declaring already on `let`, unecessary mocking, lots of different mocks for `find_by`s with different inputs always returning the same `value`, etc.

2017-02-24 16:40 UTC, abiliogp commented on spec/unit/provider/oneview_datacenter_synergy_spec.rb
> +    it 'deletes the resource' do
If I remove this line, I got this error:
1) Puppet::Type::Oneview_datacenter::ProviderSynergy given the min parameters deletes the resource
     Failure/Error: datacenter.map(&:remove)
     
     OneviewSDK::IncompleteResource:
       Please set uri attribute before interacting with this resource
     # ./lib/puppet/provider/oneview_datacenter/c7000.rb:37:in `map'
     # ./lib/puppet/provider/oneview_datacenter/c7000.rb:37:in `destroy'
     # ./spec/unit/provider/oneview_datacenter_synergy_spec.rb:113:in `block (3 levels) in <top (required)>'

2017-02-24 16:58 UTC, abiliogp commented on spec/unit/provider/oneview_enclosure_group_synergy_spec.rb
> +      resource['data']['uri'] = '/rest/fake'
If I remove this line:

```ruby
it 'deletes the resource' do
      resource['data']['uri'] = '/rest/fake'
      test = resourcetype.new(@client, resource['data'])
      allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
      allow(resourcetype).to receive(:find_by).with(anything, 'name' => resource['data']['name']).and_return([test])
      expect_any_instance_of(OneviewSDK::Client).to receive(:rest_delete).and_return(FakeResponse.new('uri' => '/rest/fake'))
      provider.exists?
      expect(provider.destroy).to be
end
```

I got this error:

1) Puppet::Type::Oneview_datacenter::ProviderSynergy given the min parameters deletes the resource
     Failure/Error: datacenter.map(&:remove)
     
     OneviewSDK::IncompleteResource:
       Please set uri attribute before interacting with this resource
     ./lib/puppet/provider/oneview_datacenter/c7000.rb:37:in `map'
     ./lib/puppet/provider/oneview_datacenter/c7000.rb:37:in `destroy'
     ./spec/unit/provider/oneview_datacenter_synergy_spec.rb:113:in `block (3 levels) in <top (required)>'

2017-02-24 17:02 UTC, abiliogp commented on spec/unit/provider/oneview_enclosure_synergy_spec.rb
> +    it 'should be able to work specifying a name instead of an uri' do
What you want to change?

2017-02-24 17:02 UTC, abiliogp commented on spec/unit/provider/oneview_enclosure_synergy_spec.rb
> +    it 'deletes the resource' do
Same as above

2017-02-24 17:05 UTC, abiliogp commented on spec/unit/provider/oneview_enclosure_synergy_spec.rb
> +      it 'creates the resource' do
Ok, make sense! :+1:

2017-02-24 17:09 UTC, abiliogp commented on spec/unit/provider/oneview_datacenter_synergy_spec.rb
> +    it 'deletes the resource' do
Are you talking about the :findby?

2017-02-24 18:36 UTC, fgbulsoni commented on spec/unit/provider/oneview_enclosure_synergy_spec.rb
> +      allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
no need for multiple find_bys for different inputs and same return, just leave one without `with`

2017-02-24 18:37 UTC, fgbulsoni commented on spec/unit/provider/oneview_enclosure_synergy_spec.rb
> +      expect_any_instance_of(OneviewSDK::Client).to receive(:rest_delete).and_return(FakeResponse.new('uri' => '/rest/fake'))
testing rest_delete is definitely not what we want here

2017-02-24 18:37 UTC, fgbulsoni commented on spec/unit/provider/oneview_enclosure_synergy_spec.rb
> +        allow(resourcetype).to receive(:find_by).with(anything, 'name' => resource['data']['name']).and_return([])
no need for the `with`

2017-02-24 18:47 UTC, fgbulsoni commented on spec/unit/provider/oneview_enclosure_synergy_spec.rb
> +      allow(resourcetype).to receive(:find_by).with(anything, resource['data']).and_return([test])
Actually, no need for any find_by, this should be in the `before_each` block

2017-02-24 18:48 UTC, fgbulsoni commented on spec/unit/provider/oneview_enclosure_synergy_spec.rb
> +        expect_any_instance_of(OneviewSDK::Client).to receive(:rest_patch)
we do not want to test rest_ calls, mock the sdk method and clean up the test

2017-02-24 18:48 UTC, fgbulsoni commented on spec/unit/provider/oneview_ethernet_network_synergy_spec.rb
> +      expect_any_instance_of(OneviewSDK::Client).to receive(:rest_delete).and_return(FakeResponse.new('uri' => '/rest/fake'))
we do not want to be testing rest_ calls

2017-02-24 18:48 UTC, fgbulsoni commented on spec/unit/provider/oneview_fcoe_network_synergy_spec.rb
> +      expect_any_instance_of(OneviewSDK::Client).to receive(:rest_delete).and_return(FakeResponse.new('uri' => '/rest/fake'))
again, no rest_ calls

2017-02-24 18:49 UTC, fgbulsoni commented on spec/unit/provider/oneview_firmware_driver_synergy_spec.rb
> +      expect_any_instance_of(OneviewSDK::Client).to receive(:rest_delete).and_return(FakeResponse.new('uri' => '/rest/fake'))
rest_...

2017-02-24 18:52 UTC, fgbulsoni requested changes
I still see many methods that need refactoring.
1. We should not be calling nor mocking the rest methods, just the sdk methods
2. If we have the test in a `let` block, and the find_by already in a `before_each` block (which we SHOULD!), we should not be calling them inside the tests unless absolutely necessary for whatever reason.
3. when mocking the sdk methods, tests should become a lot simpler, so there's also no need for lenghty `it` blocks which declare a lot of stuff inside resource, either make a different resource or those assignments should not be needed.

2017-02-24 19:24 UTC, fgbulsoni approved these changes

2017-02-24 19:27 UTC, merged