ADD support to Deployment Plan
HewlettPackard/oneview-puppet pull request #118
Opened 2017-02-23 16:52 UTC by abiliogp

### Description
Adds support to Image Streamer Deployment Plan

### Issues Resolved
#96 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] Changes are documented in the CHANGELOG.

2017-02-24 17:26 UTC, fgbulsoni commented on lib/puppet/provider/image_streamer_deployment_plan/image_streamer.rb
> +  def resource_name
This should be getting auto-set, not need for the method

2017-02-24 17:31 UTC, fgbulsoni requested changes
Few changes

2017-02-24 17:31 UTC, fgbulsoni commented on lib/puppet/provider/image_streamer_deployment_plan/image_streamer.rb
> +    golden_image_client = OneviewSDK::ImageStreamer.resource_named('GoldenImage', @client.api_version)
`golden_image_client`? isn't this the golden image **class**?

2017-02-24 17:31 UTC, fgbulsoni commented on lib/puppet/provider/image_streamer_deployment_plan/image_streamer.rb
> +    build_plan_client = OneviewSDK::ImageStreamer.resource_named('BuildPlan', @client.api_version)
client or class? Looks like class.

2017-02-24 17:31 UTC, fgbulsoni commented on lib/puppet/provider/image_streamer_deployment_plan/image_streamer.rb
> +  def self.resource_name
Should be getting auto-set, no need for the method

2017-02-24 18:16 UTC, fgbulsoni commented on lib/puppet/provider/image_streamer_deployment_plan/image_streamer.rb
> +  def parse_build_plan
both `parse_build_plan` and `parse_golden_image` should likely not be needed if making proper use of the uri_parsing methods

2017-03-01 13:46 UTC, marikrg commented on lib/puppet/provider/image_streamer_deployment_plan/image_streamer.rb
> +  def parse_build_plan
@abiliogp has created some issues to solve it later (#122 and #121)

2017-03-02 12:34 UTC, fgbulsoni approved these changes

2017-03-02 14:17 UTC, merged