Add example of how to create a Server Profile with OS Deployment Settings
HewlettPackard/oneview-puppet pull request #131
Opened 2017-03-16 19:53 UTC by marikrg

### Description
Add an example of how to create a Server Profile with OS Deployment Settings

### Issues Resolved
#126 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

2017-03-17 17:13 UTC, fgbulsoni commented
Do we need to upload an artifact bundle here? Specially one so small? I'd rather have each artifact created by the manifest to highlight exactly what we are doing here. Is it possible?

2017-03-17 17:35 UTC, marikrg commented
@fgbulsoni 
Not sure. I'm going to ask for the person who suggested this user case scenario.

2017-03-17 18:27 UTC, fgbulsoni commented
OK, it was explained to me that this zip actually contains a super small bootable image along with a few resources created. 
An issue will be opened to better extend this user story having another example where each resource declaration, from the golden image upload to each artifact being created, is performed by a single manifest and that should give clarity to the final user.
This example will be considered as accepted for the case in which we have already downloaded an artifact bundle and want to perform a deploy from there, but only once we have the issue up on github.

2017-03-17 18:28 UTC, fgbulsoni requested changes

2017-03-17 18:28 UTC, fgbulsoni commented on examples/image_streamer/server_profile_deployment_settings.pp
> +
Explain here what is contained inside the .zip and also better explain what the script will be doing.

2017-03-17 18:29 UTC, marikrg commented on examples/image_streamer/server_profile_deployment_settings.pp
> +
:+1:

2017-03-20 14:19 UTC, marikrg commented
@fgbulsoni I realised that I must assign a server hardware to make this example more complete. I'm waiting for a Server Harware be available to make this change.

2017-03-21 13:29 UTC, marikrg commented
> @fgbulsoni I realised that I must assign a server hardware to make this example more complete. I'm waiting for a Server Harware be available to make this change.

I have changed the Server Hardware affinity to Bay and Server and created a connection for management.

I still need to figure out why the added zip file is corrupted, I assume it's related with the eol config from .gitattributes.

Also pending create the issue that we we've mentioned on this conversation.

2017-03-22 12:18 UTC, marikrg commented
@fgbulsoni Done! Can you review it again?

2017-03-22 16:40 UTC, fgbulsoni requested changes

2017-03-22 16:40 UTC, fgbulsoni commented on examples/image_streamer/server_profile_deployment_settings.pp
> +# Once you run the manifest, you must:
Once this manifest is run, the following actions must be taken:

2017-03-23 12:52 UTC, fgbulsoni approved these changes

2017-03-23 13:11 UTC, merged