Documentation reviewed and updated
HewlettPackard/oneview-puppet pull request #136
Opened 2017-03-20 18:59 UTC by marikrg

### Description
Update the CHANGELOG and README documentation

### Issues Resolved
No issue.

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

2017-03-21 14:17 UTC, fgbulsoni requested changes
All changes look good.
One more suggestion:
In the resources.md, instead of having Oneview summary -> all oneview resources -> i3s summary -> all i3s resources,
how about we make it so that the summary is actually the reference to the whole document?
I'd suggest having the i3s links up there, right bellow the oneview links, for ease of searching and finding resources.

2017-03-21 17:52 UTC, marikrg commented
@fgbulsoni 

:memo: done!
Can you check it again?

2017-03-21 18:55 UTC, fgbulsoni requested changes
Missing a couple of anchors and titles

2017-03-21 18:55 UTC, fgbulsoni commented on RESOURCES.md
> +## HPE OneView resources
This should also be linking to the section where the oneview resources begin

2017-03-21 18:55 UTC, fgbulsoni commented on RESOURCES.md
>  #### oneview_connection_template
Missing a Title before the resources such as `## HPE OneView resources`, which should be linked by the summary item

2017-03-21 18:55 UTC, fgbulsoni commented on RESOURCES.md
> +## HPE Image Streamer resources
This should also be anchored to the corresponding section

2017-03-21 19:48 UTC, marikrg commented on RESOURCES.md
> +## HPE OneView resources
I'm not able to add a link on a heading.

2017-03-21 19:48 UTC, marikrg commented on RESOURCES.md
> +## HPE Image Streamer resources
I'm not able to add a link on a heading.

2017-03-22 12:10 UTC, marikrg commented on RESOURCES.md
> +## HPE OneView resources
Aesthetically, isn't good to have a link in a heading.
Specially in this case, it'll not be linked to any specific content.

2017-03-22 16:33 UTC, fgbulsoni approved these changes

2017-03-22 17:03 UTC, merged