Oneview_server_hardware_type API 300 Synergy & C7000 support
HewlettPackard/oneview-puppet pull request #48
Opened 2017-01-18 19:07 UTC by fgbulsoni

### Description
Extends support for API300 on Synergy and C7000 to resource Oneview_server_hardware_type

### Issues Resolved
#25 

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass (`$ rake test`).
- [X] New functionality has been documented in the README if applicable.
  - [X] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [X] Changes are documented in the CHANGELOG.

2017-01-19 14:09 UTC, tmiotto requested changes
Fix the copyright

2017-01-19 14:54 UTC, abiliogp approved these changes

2017-01-20 11:54 UTC, fgbulsoni commented
@tmiotto copyright fixed

2017-01-20 12:48 UTC, tmiotto approved these changes

2017-01-23 11:40 UTC, merged