Oneview_logical_downlink API 300 Support for Synergy and C7000
HewlettPackard/oneview-puppet pull request #49
Opened 2017-01-18 22:09 UTC by fgbulsoni

### Description
Expands support to API 300 for the Oneview_logical_downlink resource

### Issues Resolved
#14 

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass (`$ rake test`).
- [X] New functionality has been documented in the README if applicable.
  - [X] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [X] Changes are documented in the CHANGELOG.

2017-01-19 13:04 UTC, abiliogp requested changes
I found some codes commented out.
Please, fix that code.

2017-01-19 13:04 UTC, abiliogp commented on spec/unit/provider/oneview_logical_downlink_c7000_spec.rb
> +    # resource['data'] = {}
Why these code are commented?

2017-01-19 13:04 UTC, abiliogp commented on spec/unit/provider/oneview_logical_downlink_synergy_spec.rb
> +    # resource['data'] = {}
Why these code are commented?

2017-01-19 16:41 UTC, fgbulsoni commented on spec/unit/provider/oneview_logical_downlink_c7000_spec.rb
> +    # resource['data'] = {}
'Test disabled due to bug on oneview-sdk'

2017-01-19 16:41 UTC, fgbulsoni commented on spec/unit/provider/oneview_logical_downlink_synergy_spec.rb
> +    # resource['data'] = {}
'Test disabled due to bug on oneview-sdk' - Should be re-enabled/uncommented once oneview-sdk is fixed

2017-01-20 12:51 UTC, tmiotto commented
Maybe we could use `xit` instead commenting out so we don't lose track of it

2017-01-20 17:52 UTC, fgbulsoni commented
Commented out test changed for xit. @abiliogp please verify.

2017-01-20 18:02 UTC, abiliogp approved these changes

2017-01-23 11:40 UTC, merged