Update Rack to support version 300
HewlettPackard/oneview-puppet pull request #52
Opened 2017-01-19 19:38 UTC by abiliogp

### Description
[Describe what this change achieves]

### Issues Resolved
[List any issues this PR will resolve. e.g., Fixes #01]

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

2017-01-20 11:58 UTC, fgbulsoni requested changes
- Improve description and list the issues addressed. 
- Should also update integration tests and if needed, the examples. Make sure the integrations/examples are passing.
- Also verify code coverage

2017-01-20 11:58 UTC, fgbulsoni commented on lib/puppet/provider/oneview_rack/c7000.rb
> +# (C) Copyright 2017 Hewlett Packard Enterprise Development LP
No need to alter this

2017-01-20 11:58 UTC, fgbulsoni commented on lib/puppet/provider/oneview_rack/synergy.rb
> +  def initialize(*args)
Should not be needed anymore

2017-01-20 11:58 UTC, fgbulsoni commented on lib/puppet/provider/oneview_rack/c7000.rb
>    def initialize(*args)
Should not be needed anymore

2017-01-20 12:30 UTC, abiliogp commented on lib/puppet/provider/oneview_rack/c7000.rb
>    def initialize(*args)
def initialize(*args)?

2017-01-20 12:31 UTC, abiliogp commented on lib/puppet/provider/oneview_rack/synergy.rb
> +  def initialize(*args)
def initialize(*args)?

2017-01-23 17:38 UTC, fgbulsoni approved these changes

2017-01-24 11:11 UTC, merged