Extends support of Oneview_uplink_set for API300
HewlettPackard/oneview-puppet pull request #60
Opened 2017-01-24 11:36 UTC by marikrg

### Description
Use Oneview_uplink_set with API 300 on the Synergy and C7000 hardware variants

### Issues Resolved
https://github.com/HewlettPackard/oneview-puppet/issues/32

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

2017-01-24 11:39 UTC, marikrg commented
I'm fixing the broken build.

2017-01-24 11:42 UTC, fgbulsoni requested changes
line 42:     
``@property_hash[:data] = @data``
should be
``@property_hash[:data] = uplink_set.data``

Also, found and destroy methods are being inherited and could be dropped.

2017-01-24 16:17 UTC, marikrg commented
> I'm fixing the broken build.
Done.

2017-01-24 16:17 UTC, marikrg commented
> line 42:
> @property_hash[:data] = @data
> should be
> @property_hash[:data] = uplink_set.data
> 
> Also, found and destroy methods are being inherited and could be dropped.

Done.

2017-01-24 16:33 UTC, marikrg commented
I just noticed that the update is not working properly for Uplink Sets. I will fix it.

2017-01-25 17:19 UTC, marikrg commented
> I just noticed that the update is not working properly for Uplink Sets. I will fix it.

As we decided, we are going to fix the update later, since this resource needs a different approach (see the bug opened for oneview-ansible at: https://github.com/HewlettPackard/oneview-ansible/issues/13)

2017-01-25 17:29 UTC, fgbulsoni approved these changes

2017-01-25 22:37 UTC, fgbulsoni requested changes

2017-01-25 22:37 UTC, fgbulsoni commented on spec/unit/provider/oneview_uplink_set_c7000_spec.rb
>  resourcetype = OneviewSDK::UplinkSet
Should add something along the lines of the following code to account for different APIs
```ruby
api_version = login[:api_version] || 200
resource_name = 'UplinkSet'
resourcetype = if api_version == 200
                 Object.const_get("OneviewSDK::API#{api_version}::#{resource_name}")
               else
                 Object.const_get("OneviewSDK::API#{api_version}::C7000::#{resource_name}")
               end
```

2017-01-25 22:37 UTC, fgbulsoni commented on spec/unit/provider/oneview_uplink_set_synergy_spec.rb
> +resourcetype = OneviewSDK::UplinkSet
Should add something along the lines of:
```ruby
api_version = login[:api_version] || 200
resource_name = 'UplinkSet'
resourcetype = Object.const_get("OneviewSDK::API#{api_version}::Synergy::#{resource_name}") unless api_version < 300
```
to account for different apis

2017-01-25 22:37 UTC, fgbulsoni commented on spec/unit/provider/oneview_uplink_set_synergy_spec.rb
> +describe provider_class, unit: true do
should add 
```ruby
if: api_version >= 300
```
to avoid this test running for API 200

2017-01-26 13:33 UTC, fgbulsoni approved these changes

2017-01-26 13:46 UTC, merged