Add support to the Oneview_sas_interconnect resource
HewlettPackard/oneview-puppet pull request #74
Opened 2017-01-26 20:13 UTC by fgbulsoni

### Description
Adds support to the Oneview_sas_interconnect resource

### Issues Resolved
#73 

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass (`$ rake test`).
- [X] New functionality has been documented in the README if applicable.
  - [X] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

2017-01-30 19:54 UTC, abiliogp commented on lib/puppet/provider/oneview_sas_interconnect/synergy.rb
> +  def found
Is it necessary?

2017-01-31 13:39 UTC, tmiotto requested changes

2017-01-31 13:39 UTC, tmiotto commented on lib/puppet/provider/oneview_sas_interconnect/synergy.rb
> +    if @data['name']
```ruby
pretty if ...
         ret_val1
       else
         ret_val2
```

2017-01-31 13:39 UTC, tmiotto commented on lib/puppet/type/oneview_sas_interconnect.rb
> +      raise('Inserted value for data is not valid') unless value.class == Hash
duck typing maybe? `[]=`

2017-01-31 15:33 UTC, fgbulsoni commented on lib/puppet/provider/oneview_sas_interconnect/synergy.rb
> +    if @data['name']
Really good, unfortunately ruby seems to not like it :cry: I can assign a variable on an if block, but not puts the output of an if block. Would have to first assign the output to a variable and then pretty it, which would just add one extra line and assignment to save one pretty.
Gonna keep as is since the change does not seem beneficial.

2017-01-31 17:49 UTC, tmiotto approved these changes

2017-01-31 20:00 UTC, merged