ADD idempotency for server profile
HewlettPackard/oneview-puppet pull request #94
Opened 2017-02-10 17:12 UTC by abiliogp

### Description
ADD idempotency for Server Profile, it was tested in Synergy and C7000. 

### Issues Resolved
Allow Server Profile client to make the same call with same data repeatedly, and producing the same result.

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

2017-02-10 17:57 UTC, fgbulsoni requested changes

2017-02-10 17:57 UTC, fgbulsoni commented on lib/puppet/provider/oneview_server_profile/c7000.rb
>      @data = data_parse
Maybe swap line 27+28 for super([:found, :get_avai(...)])

2017-02-10 17:57 UTC, fgbulsoni commented on lib/puppet/provider/oneview_server_profile/c7000.rb
> +           @resourcetype.find_by(@client, @data)
Lines 36-42 could be better employing a guard clause.
```ruby
return @resourcetype.find_by(@client, @data).any? unless resource['ensure'] == :present
resource_update(@data, @resourcetype)
@resourcetype.find_by(@client, unique_id).any?
```

2017-02-13 10:15 UTC, fgbulsoni commented
Probably good to also add this improvement in the [changelog](CHANGELOG.md).
Something like:
# Unreleased Changes

## Suggested release: v3.2.0

#### Bug fixes & Enhancements:
- [#95](https://github.com/HewlettPackard/oneview-puppet/issues/95) Improve server profile idempotency

2017-02-13 15:29 UTC, fgbulsoni commented on CHANGELOG.md
> +# Unreleased Changes
This section should be on the first line, not last. The changelog order is: most recent to least recent

2017-02-13 15:30 UTC, fgbulsoni commented on CHANGELOG.md
> +## Suggested release: v3.2.0
Also, v2.2.0 (I made a typo on the comment)

2017-02-14 13:50 UTC, fgbulsoni requested changes
Due to the PR #102 I'm kind of questioning the relevance of this PR now.
What exactly is being done here that was not before? If the state is present it is currently applying the update and returning true, which is basically what would be done anyway on the 'create' method.
As it is, I don't think this is adding much/any value. Please lemme know if I'm overlooking something.

Also, definitely a must now, more than before, to have the scenarios for which the server profile fails to perform idempotently and against which this PR was ran added to the PR and/or to the issue related.

2017-02-14 13:50 UTC, fgbulsoni commented on lib/puppet/provider/oneview_server_profile/c7000.rb
> +    return @resourcetype.find_by(@client, @data).any? unless resource['ensure'] == :present
Due to the PR #102 I'm kind of questioning the relevance of this PR now.
What exactly is being done here that was not before? If the state is present it is currently applying the update and returning true, which is basically what would be done anyway on the 'create' method.
As it is, I don't think this is adding much/any value. Please lemme know if I'm overlooking something.

Also, definitely a must now, more than before, to have the scenarios for which the server profile fails to perform idempotently and against which this PR was ran added to the PR and/or to the issue related.

2017-02-14 15:27 UTC, abiliogp commented on lib/puppet/provider/oneview_server_profile/c7000.rb
> +    return @resourcetype.find_by(@client, @data).any? unless resource['ensure'] == :present
For the idempotency it's needed to compare and update data, this is made by resource_update only when ensure is present.

2017-02-14 18:27 UTC, closed without merging